Minor fixes to main layout
akropolisio/akropolisOS-frontend pull request #80
Opened 2020-07-10 18:07 UTC by imin314

2020-07-11 12:25 UTC, sk1e requested changes

2020-07-11 12:25 UTC, sk1e commented on src/app/components/CreditPoolHeader/components/AppButton/AppButton.style.ts
> +  { name: 'appButton' },
I am using dash case (app-button) for such names, let's follow single naming scheme to keep consistency

2020-07-11 12:25 UTC, sk1e commented on src/app/components/NewHeader/NewHeader.style.ts
> +        fontSize: theme.spacing(5),
Was this code copied? We've come to using pixels instead of theme.spacing for new components

2020-07-13 07:08 UTC, in19farkt commented on src/app/pages/CreditPool/Intro/Intro.tsx
> +        {/* <Button
Remove comment

2020-07-13 07:09 UTC, in19farkt commented on src/components/Layout/Layout.style.ts
> +  root: {
Remove unused classes

2020-07-13 07:11 UTC, in19farkt commented on src/services/theme/ThemeButton/ThemeButton.style.ts
> +    backgroundColor: theme.palette.type === 'light' ? theme.colors.athensGray : theme.colors.obsidian,
prettier error

2020-07-13 10:16 UTC, in19farkt approved these changes

2020-07-13 10:16 UTC, merged