Use icon button in sidebar
akropolisio/akropolisOS-frontend pull request #88
Opened 2020-07-15 10:21 UTC by imin314

2020-07-15 11:19 UTC, sk1e commented on src/app/components/Sidebar/Sidebar.tsx
> -  function renderSwitch() {
why removed?

2020-07-15 11:24 UTC, in19farkt submitted a review, later dismissed

2020-07-15 11:25 UTC, sk1e requested changes

2020-07-15 11:25 UTC, sk1e commented on src/app/components/Sidebar/icons/Switch.tsx
> +export const Switch: React.FC<GetProps<typeof SvgIcon>> = props => {
replace GetProps with React.ComponentProps

2020-07-16 06:40 UTC, sk1e submitted a review, later dismissed

2020-07-16 11:55 UTC, in19farkt approved these changes

2020-07-16 11:55 UTC, merged